### PR TITLE
- Added support for prefilled data

### PR DESCRIPTION
**Pull request by avishayil**
@noamtamim Can you please review?

### CODE REVIEW

**Comment by avishayil** [comment]
Addresses #1

**Comment by noamtamim** [comment]
I'm not a React developer, though the code looks good. That said -- how does the query string get to the URL - does the user have to add it manually? I don't see anything that sets `location.href` or that creates a reusable link.

There might be a React magic that does it, though...

**Comment by avishayil** [comment]
Good point. I think the solution would be to add a link / button that saves the URL to the favorites for quick access later. WDYT?

**Comment by noamtamim** [comment]
Not a fan of "add bookmark" buttons, if that's what you mean. Instead, add a button that sets the current URL using [history.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState):
```javascript
history.pushState({}, null, '?childName=...&childId=...parentName=...&parentId=...');
```

Then the user can just bookmark the currentURL.
As I wrote -- I'm not a React developer; there's probably something in React that does this sort of manipulation, for the benefit of SPAs.

**Comment by noamtamim** [comment]
Another way, without messing with history/routing - add a link that always contains the full URL, with the current values of the fields.
Apologies if *that's* what you meant in your comment above, I thought you mean something like [that](https://stackoverflow.com/questions/45415678/is-this-possible-to-bookmark-a-page-with-html-button).

**Comment by avishayil** [comment]
Thanks for the tips @noamtamim, you are truly thinking about the user experience.

I'm wondering if the user will even think to independently add the link to his favorites (is favorites a popular option on mobile browsers?)

Maybe we can utilize something like "add to home" on Android which will provide App-like experience for SPA. On iPhone I think there is a similar behavior, not sure if those browser APIs are exposed to JavaScript, though.

I guess that most of the users will click on that link from some WhatsApp group they first heard about the app(where did you hear about it?) Maybe some research will be useful here. In this case they will need to know about this kind of functionality in an accessible way before they will start using it rather reopening the link from WhatsApp.

Another thing will be to convert the form to support autofill by browsers, which it currently doesn't, from some reason. I'm not a React developer too, but it's always nice to do these side projects anyway.

WDYT?

**Comment by noamtamim** [comment]
> Thanks for the tips @noamtamim, you are truly thinking about the user experience.

I'm mainly thinking about myself as the user :-)

> I'm wondering if the user will even think to independently add the link to his favorites (is favorites a popular option on mobile browsers?)

I agree bookmarks are not very popular there, but I think it's mostly because it's very easy to start typing the site you're after and auto-complete (based on your history + Google) finds it for you instantly. However, there are certain cases where there's an actual benefit in saving the address - such as this one...

> Maybe we can utilize something like "add to home" on Android which will provide App-like experience for SPA. On iPhone I think there is a similar behavior, not sure if those browser APIs are exposed to JavaScript, though.

The trouble with this approach is when you have multiple kids. I'm not sure people will like multiple home shortcuts - I could be wrong though. It's an option, I guess.

> I guess that most of the users will click on that link from some WhatsApp group they first heard about the app(where did you hear about it?) Maybe some research will be useful here. In this case they will need to know about this kind of functionality in an accessible way before they will start using it rather reopening the link from WhatsApp.

I got to it from Twitter, someone forwarded the link. And I didn't initially need it, because the school + preschool have their own digital systems. But now the school is over, and from time to time there are activities that require it. Plus, I think it's nice to have something like that online.

> Another thing will be to convert the form to support autofill by browsers, which it currently doesn't, from some reason. I'm not a React developer too, but it's always nice to do these side projects anyway.

I don't know how it's done; in my day job, I mainly develop for iOS and Android. I do have some JS background, so from time to time I fix things here and there.

> WDYT?

I think it it might be nice and simple to have a button "צור לינק לשימוש חוזר". This button will push the pre-filled URL to the history and then notify the user that he should now bookmark or save the page.

**Comment by avishayil** [comment]
Awesome @noamtamim. I think a notification about this feature is important. I think I'll find some kind of alerting mechanism (and cookies) to notify about the new feature.

So if I'm trying to summarize the flow (assuming not all users are high-tech workers :), with pardon):
- User is entering the website, entering the details.
- Notification that encourages the user to add the page to the favorites will pop. Need to find a good component for that (feature highlight Walkme-like). The notification will save a cookie that the user already saw it.
- After all the form boxes are filled, a logic will push the page to the browser's history for easier access via URL.
- I'll investigate a way to utilize auto-fill for convenience.

Did I miss anything?

**Comment by noamtamim** [comment]
For your second bullet, I'm not sure such a complex mechanism is required. The users already know they need to press the black button to get the image - you can use that event to notify the users about this feature.
Anyway, sounds like a good plan. I don't know what's the required effort, though - might be a good idea to merge this pull as-is, and open a new one for the extras.

**Comment by avishayil** [comment]
I opened issues for each feature discussed here, if you like to continue to contribute to this repository, i'd be happy to collaborate.

**Pull request merged**
